### ISSUE TITLE
Fretboard End Overhang

### ISSUE THREAD

**Issue by Jamieip** [acspike/FretFind2D#4]
a 24 fret fret board would need 24 frets + extra at the end to accommodate the 24th. I usually use 25 frets for a 24 fret board. The 25th fret marks the end of the board. Something to be included

**Comment by Prostheta** [comment]
Unsure whether this qualifies as a feature for deriving mathematically-placed items or simply convenience. Sounds like you answered your own question? :-)

**Comment by acspike** [comment]
Adding an extra fret to your design to reserve the space for the end of the fretboard sounds like a perfect solution.
